Initial commit
fortinet-fortisoar/connector-ibm-security-guardium-insights pull request #1
Opened 2023-07-04 07:42 UTC by cs-harsh-sharma

### Descriptions:

IBM Security Guardium Insights connector helps in protecting sensitive on-premises and cloud data. The connector comprises of following actions:

Function | Description
-- | --
Get Report Categories List | Retrieves the list of all the available report categories from IBM Guardium Insights based on the input parameters specified.
Get Reports List | Retrieves the list of all the reports from IBM Guardium Insights based on the input parameters specified.
Get Policies List | Retrieves the list of all the policies from IBM Guardium Insights.
Get Policy Details | Retrieves the details of the policy from IBM Guardium Insights based on the policy ID specified.
Get Cases List | Retrieves the list of all the cases from IBM Guardium Insights based on the input parameters specified.
Get Tasks List | Retrieves the list of all the tasks from IBM Guardium Insights based on the input parameters specified.
Get Groups List | Retrieves the list of all the groups from IBM Guardium Insights.
Get Group Members List | Retrieves the list of all the members of the group from IBM Guardium Insights based on the group ID specified.
Get Compliance Data | Retrieves the compliance data from IBM Guardium Insights.
Get Connections List | Retrieves the list of all the connections accounts from IBM Guardium Insights based on the input parameters specified.
Get Datasets List | Retrieves the list of all the datasets from IBM Guardium Insights based on the input parameters specified.
Get Dataset Data | Retrieves the data report of specified dataset from IBM Guardium Insights.
Get Notifications List | Retrieves the list of all the notifications from IBM Guardium Insights based on the input parameters specified.
Get Schedules List | Retrieves the list of all the scheduled jobs and the linked tasks from IBM Guardium Insights based on the input parameters specified.
Get Scheduled Job Details | Retrieves the details of the scheduled job from IBM Guardium Insights based on the schedule ID specified.

2023-07-04 09:26 UTC, cs-utkarsh-surana requested changes

2023-07-04 09:26 UTC, cs-utkarsh-surana commented on ibm-security-guardium-insights/info.json
> +        "type": "text",
The type should be password.

2023-07-04 09:33 UTC, cs-harsh-sharma commented on ibm-security-guardium-insights/info.json
> +        "type": "text",
done

2023-07-10 06:48 UTC, cs-renuka-andhale approved these changes
LGTM.

2023-07-10 10:00 UTC, merged